Golang logo
midudev/miduconf-website pull request #91
Opened 2023-09-06 22:44 UTC by jonathanhecl

Golang logo

2023-09-07 13:57 UTC, jonathanhecl commented
Ahora no hay conflictos, pero sigue molestandose.

2023-09-08 18:10 UTC, FabianMontoya commented on src/flavors/data.tsx
> +		component: ({ className }) => (
Creo que te falta añadir `<svg className={className}`

2023-09-08 18:17 UTC, FabianMontoya requested changes
Agrega el `className`, creo que es lo que está fallando

2023-09-08 18:33 UTC, jonathanhecl commented
No, no quiere verificarse, aunque no tenga NADA diferente, no deja. Una pena.
@midudev

2023-09-08 18:46 UTC, FabianMontoya commented
@jonathanhecl no sé que era pero hice tu cambio corrigiendo algunas cosas con el SVG que querías subir, ahí te dejo como referencia: #109 

Ya puedes cerrar éste

2023-09-08 18:48 UTC, closed without merging